
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - kafka-network
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mongo-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mongo-network

  kafkaP:
    image: kafka-producer:latest
    container_name: kafkaP
    networks:
      - kafka-network
    depends_on:
      - kafka

  kafkaC:
    image: kafka-consumer:latest
    container_name: kafkaC
    networks:
      - kafka-network
      - mongo-network
    depends_on:
      - kafka
      - mongo

  etl:
    image: etl-service:latest
    container_name: etl
    networks:
      - mongo-network
    depends_on:
      - mongo
      - redis

networks:
  kafka-network:
    driver: bridge
  mongo-network:
    driver: bridge
